# Optional dependencies left out: mpmath, gmpy2, libsuitesparse, 
# libgmp,libmpfr, libsuitesparse, libmpc, sparse, scikit-umfpack
name: scipydev 
dependencies:
  - pytest=6.2.1
  - pybind11=2.6.1
  - compilers=1.1.3
  - matplotlib=3.3.3
  - numpy=1.19.5
  - mypy=0.800
  - python=3.8
  - sphinx=3.4.3
  - pydata-sphinx-theme=0.5.0
  - cython=0.29.21
  - pythran=0.9.8.post2
  - ipython=7.19.0  # that version has working autocompletion it looks like
  - conda-build=3.21.4
  - openblas=0.3.12
  - pip
  - pip:
    - numpydoc>=1.1.0
    - asv>=0.4.2
    - flake8