name: "Label PR on Close"
on:
  pull_request_target:
    types: [closed]

jobs:
  label_pull_request:
    name: "Label PR on Close"
    # Permissions needed for labelling Pull Requests automatically
    # https://docs.github.com/en/actions/security-guides/automatic-token-authentication
    permissions:
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
    - uses: github/issue-labeler@c1b0f9f52a63158c4adc09425e858e87b32e9685 # v3.4
      if: >
        github.repository == 'nickodell/scipy'
        && github.event.pull_request.merged == true
      with:
        configuration-path: .github/label-title-on-close.yml
        include-title: 1
        include-body: 0
        enable-versioned-regex: 0
        repo-token: ${{ secrets.GITHUB_TOKEN }}
