name: Test musllinux_x86_64

on:
  push:
    branches:
      - maintenance/**
  pull_request:
    branches:
      - main
      - maintenance/**

permissions:
   contents: read  # to fetch code (actions/checkout)


concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true


jobs:
  get_commit_message:
    name: Get commit message
    uses: ./.github/workflows/commit_message.yml

  musllinux_x86_64:
    needs: get_commit_message
    runs-on: ubuntu-latest
    # If using act to run CI locally the github object does not exist and
    # the usual skipping should not be enforced
    if: >
      needs.get_commit_message.outputs.message == 1
      && (github.repository == 'scipy/scipy' || github.repository == '')
    container:
      # Use container used for building musllinux wheels
      # it has git installed, all the pythons, etc
      image: quay.io/pypa/musllinux_1_1_x86_64


    steps:
    - name: Get source
      run: |    
        apk update --quiet

        apk add build-base gfortran git

        git config --global --add safe.directory $PWD 
        
        if [ $GITHUB_EVENT_NAME != pull_request ]; then
            git clone --recursive --branch=$GITHUB_REF_NAME https://github.com/${GITHUB_REPOSITORY}.git $GITHUB_WORKSPACE
            git reset --hard $GITHUB_SHA
        else        
            git clone --recursive https://github.com/${GITHUB_REPOSITORY}.git $GITHUB_WORKSPACE
            git fetch origin $GITHUB_REF:my_ref_name
            git checkout $GITHUB_BASE_REF
            git -c user.email="you@example.com" merge --no-commit my_ref_name
        fi

        ln -s /usr/local/bin/python3.10 /usr/local/bin/python
        git submodule update --init


    - name: prep build environment
      run: |    
        cd $RUNNER_TEMP
        python -m venv test_env
        source test_env/bin/activate
        cd $GITHUB_WORKSPACE

        python -m pip install cython numpy
        # python -m pip install --upgrade --pre -i https://pypi.anaconda.org/scientific-python-nightly-wheels/simple numpy
        python -m pip install meson ninja pybind11 pythran pytest hypothesis
        python -m pip install click rich_click doit pydevtool pooch
        
        chmod +x tools/wheels/cibw_before_build_linux.sh
        tools/wheels/cibw_before_build_linux.sh --nightly .     

    - name: test
      run: |
        set -xe -o
        cd $RUNNER_TEMP
        source test_env/bin/activate
        cd $GITHUB_WORKSPACE
        python dev.py test
